FROM python:3.6

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install gunicorn

COPY config/ /usr/src/app/config
COPY static/ /usr/src/app/static
COPY templates/ /usr/src/app/templates
COPY sanity_gui/ /usr/src/app/sanity_gui
COPY sanityapp/ /usr/src/app/sanityapp
COPY submissionapp/ /usr/src/app/submissionapp

RUN apt-get update && apt-get install -y vim
    
EXPOSE 8000

CMD ["gunicorn", "sanity_gui.wsgi", "-b", "0.0.0.0:8000", "--workers", "8"]